name: Build Kernel

on:
  push:
    branches: 
      - main
  workflow_dispatch: # 支持在 GitHub 页面手动点击运行

env:
  # clang 编译器选择 google lineage llvm
  # ZTE UMS9620 内核 build.config.common 官方工具链是 clang-r416183b，
  # 对应 lineage 选项 (LineageOS/android_prebuilts_clang_kernel_linux-x86_clang-r416183b)
  CLANG: "lineage"
  GKI: true
  OUTPATH: "out_artifacts"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      - name: 获取 action 和 patches
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            patches
          fetch-depth: 1
    
      - name: 设置 ubuntu-latest 依赖
        uses: ./.github/depend/ubuntu
      
      - name: clang 编译器
        if: env.CLANG
        uses: ./.github/clang

      - name: 内核源代码
        if: true
        uses: ./.github/source
      
      - name: 支持 DroidSpaces 的内核配置
        if: true
        uses: ./.github/droidspaces
      
      - name: 构建内核
        if: true
        uses: ./.github/build
      
      - name: 上传物品
        uses: ./.github/upload
